---
# Purpose: Template the squid configuration file
# Last Updated: 2018.06.11
# Notes:
  
  
- name: Regenerate /etc/squid/squid.conf file
  template:
    dest: /etc/squid/squid.conf
    src: templates/etc/squid/squid.conf.j2
    owner: proxy
    group: proxy
    backup: yes
  notify: "Restart Squid Service"

