---
# Purpose: Install squid package and dependencies
# Last Updated: 2018.06.11
# Notes:

- debug: var=ansible_os_family

- name: Install Squid
  package: 
    name: "{{ squid_package }}"
    state: latest
  # Implied enable service
  notify: "Start Squid Service"

